name: TruffleHog Secret Scan

on:
  pull_request:
    branches:
      - main  # Change if needed

permissions:
  contents: read
  pull-requests: read

jobs:
  trufflehog_scan:
    name: Secret Scan with TruffleHog
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for diff comparison

      - name: Fetch Base Branch
        run: |
          BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          git fetch origin $BASE_BRANCH --depth=1

      - name: Get Changed Files
        id: changed-files
        run: |
          BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          CHANGED_FILES=$(git diff --name-only origin/$BASE_BRANCH HEAD)
          echo "Changed files: $CHANGED_FILES"
          echo "FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Install TruffleHog (Latest)
        run: |
          pip install --upgrade trufflehog

      - name: Run TruffleHog on Repository and Filter Changed Files
        run: |
          if [[ -z "$FILES" ]]; then
            echo "✅ No changed files to scan."
            exit 0
          fi

          echo "🔍 Running TruffleHog on the repository..."
          trufflehog filesystem --json . | tee trufflehog_results.json

          echo "🔎 Filtering results for changed files..."
          FOUND=false
          for file in $FILES; do
            if grep -q "$file" trufflehog_results.json; then
              echo "❌ Secret detected in $file!"
              FOUND=true
            fi
          done

          if [[ "$FOUND" == "true" ]]; then
            echo "❌ Secrets detected! Failing the job."
            exit 1
          else
            echo "✅ No secrets found in changed files."
          fi
